module Orchestrator.Workflow
    ( writeCiWorkflow
    , writeReleaseWorkflow
    , writeSecurityWorkflow
    ) where

import System.Directory (createDirectoryIfMissing)

workflowDir :: FilePath
workflowDir = ".github/workflows"

ensureDir :: IO ()
ensureDir = createDirectoryIfMissing True workflowDir

-- | Write the CI workflow (deduplicated, clean).
writeCiWorkflow :: IO ()
writeCiWorkflow = do
    ensureDir
    writeFile (workflowDir ++ "/ci.yml") ciYaml
    putStrLn "  wrote ci.yml"

-- | Write the release workflow with multi-format packaging.
writeReleaseWorkflow :: IO ()
writeReleaseWorkflow = do
    ensureDir
    writeFile (workflowDir ++ "/release.yml") releaseYaml
    putStrLn "  wrote release.yml"

-- | Write the security workflow.
writeSecurityWorkflow :: IO ()
writeSecurityWorkflow = do
    ensureDir
    writeFile (workflowDir ++ "/security.yml") securityYaml
    putStrLn "  wrote security.yml"

ciYaml :: String
ciYaml = unlines
    [ "name: CI"
    , ""
    , "on:"
    , "  push:"
    , "    branches: [\"main\"]"
    , "  pull_request:"
    , ""
    , "concurrency:"
    , "  group: ci-${{ github.ref }}"
    , "  cancel-in-progress: true"
    , ""
    , "permissions:"
    , "  contents: read"
    , ""
    , "jobs:"
    , "  ci-gate:"
    , "    name: CI Gate"
    , "    runs-on: [self-hosted, gentoo]"
    , "    timeout-minutes: 30"
    , "    steps:"
    , "      - name: Clean workspace"
    , "        run: rm -rf \"$GITHUB_WORKSPACE\"/* \"$GITHUB_WORKSPACE\"/.??* 2>/dev/null || true"
    , "      - uses: actions/checkout@v4"
    , "        with:"
    , "          clean: false"
    , "      - uses: dtolnay/rust-toolchain@stable"
    , "        with:"
    , "          components: rustfmt, clippy"
    , "      - uses: Swatinem/rust-cache@v2"
    , ""
    , "      - name: Formatting check"
    , "        run: cargo fmt --all --check"
    , ""
    , "      - name: Clippy lint"
    , "        run: cargo clippy --workspace --all-targets -- -D warnings"
    , ""
    , "      - name: Unit and integration tests"
    , "        run: cargo test --all-targets"
    , ""
    , "  regression:"
    , "    name: Full Regression"
    , "    needs: ci-gate"
    , "    runs-on: [self-hosted, gentoo]"
    , "    timeout-minutes: 30"
    , "    env:"
    , "      DOCKER_RUNNER_CACHE: /tmp/docker-runner"
    , "      DOCKER_RUNNER_PRUNE: \"true\""
    , "    steps:"
    , "      - name: Clean workspace"
    , "        run: rm -rf \"$GITHUB_WORKSPACE\"/* \"$GITHUB_WORKSPACE\"/.??* 2>/dev/null || true"
    , "      - uses: actions/checkout@v4"
    , "        with:"
    , "          clean: false"
    , "      - name: Initialize Docker runner cache"
    , "        run: mkdir -p /tmp/docker-runner/{images,cache,artifacts}"
    , "      - name: Full regression (Docker)"
    , "        run: bash .github/scripts/docker-runner.sh rust:1.93-bookworm \"rustup component add rustfmt clippy && cargo fmt --all -- --check && cargo clippy --workspace --all-targets -- -D warnings && cargo test --all-targets && ./scripts/regression.sh\""
    ]

releaseYaml :: String
releaseYaml = unlines
    [ "name: Release"
    , ""
    , "on:"
    , "  push:"
    , "    tags:"
    , "      - \"v*\""
    , ""
    , "permissions:"
    , "  contents: write"
    , "  id-token: write"
    , "  attestations: write"
    , ""
    , "jobs:"
    , "  verify:"
    , "    name: Verify Before Release"
    , "    runs-on: [self-hosted, gentoo]"
    , "    timeout-minutes: 30"
    , "    steps:"
    , "      - name: Clean workspace"
    , "        run: rm -rf \"$GITHUB_WORKSPACE\"/* \"$GITHUB_WORKSPACE\"/.??* 2>/dev/null || true"
    , "      - uses: actions/checkout@v4"
    , "        with:"
    , "          clean: false"
    , "      - uses: dtolnay/rust-toolchain@stable"
    , "        with:"
    , "          components: rustfmt, clippy"
    , "      - uses: Swatinem/rust-cache@v2"
    , ""
    , "      - name: Verify tag matches Cargo version"
    , "        run: |"
    , "          CARGO_VERSION=\"$(awk -F'\"' '$1 ~ /^version = / { print $2; exit }' Cargo.toml)\""
    , "          TAG_VERSION=\"${GITHUB_REF_NAME#v}\""
    , "          if [ \"$CARGO_VERSION\" != \"$TAG_VERSION\" ]; then"
    , "            echo \"Tag version ($TAG_VERSION) does not match Cargo.toml version ($CARGO_VERSION)\""
    , "            exit 1"
    , "          fi"
    , ""
    , "      - name: Formatting check"
    , "        run: cargo fmt --all -- --check"
    , ""
    , "      - name: Clippy lint"
    , "        run: cargo clippy --workspace --all-targets -- -D warnings"
    , ""
    , "      - name: Unit and integration tests"
    , "        run: cargo test --all-targets"
    , ""
    , "      - name: Full regression (Docker SSH flow)"
    , "        run: ./scripts/regression.sh"
    , ""
    , "  build:"
    , "    name: Build (${{ matrix.target }})"
    , "    needs: verify"
    , "    runs-on: ${{ matrix.runner }}"
    , "    strategy:"
    , "      fail-fast: false"
    , "      matrix:"
    , "        include:"
    , "          - target: x86_64-unknown-linux-gnu"
    , "            bin: cyberdeck"
    , "            runner: ubuntu-latest"
    , "          - target: aarch64-unknown-linux-gnu"
    , "            bin: cyberdeck"
    , "            runner: ubuntu-latest"
    , "            cross: true"
    , "          - target: x86_64-apple-darwin"
    , "            bin: cyberdeck"
    , "            runner: macos-13"
    , "          - target: aarch64-apple-darwin"
    , "            bin: cyberdeck"
    , "            runner: macos-latest"
    , "          - target: x86_64-pc-windows-msvc"
    , "            bin: cyberdeck.exe"
    , "            runner: windows-latest"
    , "    steps:"
    , "      - uses: actions/checkout@v4"
    , "      - uses: dtolnay/rust-toolchain@stable"
    , "        with:"
    , "          targets: ${{ matrix.target }}"
    , "      - uses: Swatinem/rust-cache@v2"
    , "        with:"
    , "          key: ${{ matrix.target }}"
    , ""
    , "      - name: Install cross-compilation tools (aarch64 Linux)"
    , "        if: matrix.cross"
    , "        run: |"
    , "          sudo apt-get update"
    , "          sudo apt-get install -y gcc-aarch64-linux-gnu"
    , "          echo \"CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER=aarch64-linux-gnu-gcc\" >> $GITHUB_ENV"
    , ""
    , "      - name: Build release binary"
    , "        run: cargo build --release --locked --target ${{ matrix.target }}"
    , ""
    , "      - name: Package tar.gz (Linux/macOS)"
    , "        id: package_unix"
    , "        if: runner.os != 'Windows'"
    , "        shell: bash"
    , "        run: |"
    , "          mkdir -p dist"
    , "          cp \"target/${{ matrix.target }}/release/${{ matrix.bin }}\" \"dist/${{ matrix.bin }}\""
    , "          VERSION=\"${GITHUB_REF_NAME#v}\""
    , "          ARCHIVE=\"cyberdeck-${VERSION}-${{ matrix.target }}.tar.gz\""
    , "          tar -C dist -czf \"$ARCHIVE\" \"${{ matrix.bin }}\""
    , "          echo \"archive=$ARCHIVE\" >> \"$GITHUB_OUTPUT\""
    , ""
    , "      - name: Package zip (Windows)"
    , "        id: package_windows"
    , "        if: runner.os == 'Windows'"
    , "        shell: pwsh"
    , "        run: |"
    , "          New-Item -ItemType Directory -Force -Path dist | Out-Null"
    , "          Copy-Item \"target/${{ matrix.target }}/release/${{ matrix.bin }}\" \"dist/${{ matrix.bin }}\""
    , "          $version = $env:GITHUB_REF_NAME.Substring(1)"
    , "          $archive = \"cyberdeck-$version-${{ matrix.target }}.zip\""
    , "          Compress-Archive -Path \"dist/${{ matrix.bin }}\" -DestinationPath $archive -Force"
    , "          \"archive=$archive\" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append"
    , ""
    , "      - name: Attest build provenance"
    , "        uses: actions/attest-build-provenance@v2"
    , "        with:"
    , "          subject-path: ${{ steps.package_unix.outputs.archive || steps.package_windows.outputs.archive }}"
    , ""
    , "      - name: Upload artifact"
    , "        uses: actions/upload-artifact@v4"
    , "        with:"
    , "          name: release-${{ matrix.target }}"
    , "          path: |"
    , "            *.tar.gz"
    , "            *.zip"
    , ""
    , "  package:"
    , "    name: Build Linux Packages"
    , "    needs: build"
    , "    runs-on: ubuntu-latest"
    , "    steps:"
    , "      - uses: actions/checkout@v4"
    , "      - name: Download Linux binary"
    , "        uses: actions/download-artifact@v4"
    , "        with:"
    , "          name: release-x86_64-unknown-linux-gnu"
    , "          path: release-assets"
    , ""
    , "      - name: Extract binary"
    , "        run: |"
    , "          cd release-assets"
    , "          tar xzf cyberdeck-*.tar.gz"
    , "          chmod +x cyberdeck"
    , ""
    , "      - name: Build RPM"
    , "        run: bash packaging/build-packages.sh rpm"
    , ""
    , "      - name: Build DEB"
    , "        run: bash packaging/build-packages.sh deb"
    , ""
    , "      - name: Build Pacman"
    , "        run: bash packaging/build-packages.sh pacman"
    , ""
    , "      - name: Upload packages"
    , "        uses: actions/upload-artifact@v4"
    , "        with:"
    , "          name: linux-packages"
    , "          path: |"
    , "            packaging/output/*.rpm"
    , "            packaging/output/*.deb"
    , "            packaging/output/*.pkg.tar.zst"
    , ""
    , "  publish:"
    , "    name: Publish GitHub Release"
    , "    needs: [build, package]"
    , "    runs-on: ubuntu-latest"
    , "    steps:"
    , "      - name: Download all artifacts"
    , "        uses: actions/download-artifact@v4"
    , "        with:"
    , "          pattern: release-*"
    , "          merge-multiple: true"
    , "          path: release-assets"
    , ""
    , "      - name: Download Linux packages"
    , "        uses: actions/download-artifact@v4"
    , "        with:"
    , "          name: linux-packages"
    , "          path: release-assets"
    , ""
    , "      - name: Publish release"
    , "        uses: softprops/action-gh-release@v2"
    , "        with:"
    , "          files: release-assets/*"
    , "          generate_release_notes: true"
    ]

securityYaml :: String
securityYaml = unlines
    [ "name: Security"
    , ""
    , "on:"
    , "  push:"
    , "    branches: [\"main\"]"
    , "  pull_request:"
    , "  workflow_dispatch:"
    , "  schedule:"
    , "    - cron: \"0 6 * * 1\""
    , ""
    , "concurrency:"
    , "  group: security-${{ github.ref }}"
    , "  cancel-in-progress: true"
    , ""
    , "permissions:"
    , "  contents: read"
    , "  security-events: write"
    , ""
    , "jobs:"
    , "  security-scan:"
    , "    name: Security Scan"
    , "    runs-on: [self-hosted, gentoo]"
    , "    steps:"
    , "      - name: Clean workspace"
    , "        run: rm -rf \"$GITHUB_WORKSPACE\"/* \"$GITHUB_WORKSPACE\"/.??* 2>/dev/null || true"
    , "      - uses: actions/checkout@v4"
    , "        with:"
    , "          clean: false"
    , "          fetch-depth: 0"
    , "      - uses: dtolnay/rust-toolchain@stable"
    , "        with:"
    , "          components: clippy"
    , "      - uses: Swatinem/rust-cache@v2"
    , "      - uses: taiki-e/install-action@cargo-audit"
    , ""
    , "      - name: Cargo audit"
    , "        run: cargo audit"
    , ""
    , "      - name: Install cargo-deny"
    , "        run: cargo install cargo-deny --locked"
    , ""
    , "      - name: Cargo deny check"
    , "        run: cargo deny check --config deny.toml --hide-inclusion-graph bans licenses sources"
    , ""
    , "      - name: Clippy (deny warnings)"
    , "        run: cargo clippy --all-targets -- -D warnings"
    , ""
    , "      - name: Install Gitleaks"
    , "        run: |"
    , "          if command -v gitleaks >/dev/null 2>&1; then"
    , "            gitleaks version"
    , "            exit 0"
    , "          fi"
    , "          version=\"8.24.3\""
    , "          arch=\"$(uname -m)\""
    , "          case \"${arch}\" in"
    , "            x86_64)  archive=\"gitleaks_${version}_linux_x64.tar.gz\" ;;"
    , "            aarch64|arm64) archive=\"gitleaks_${version}_linux_arm64.tar.gz\" ;;"
    , "            *) echo \"Unsupported arch: ${arch}\"; exit 1 ;;"
    , "          esac"
    , "          url=\"https://github.com/gitleaks/gitleaks/releases/download/v${version}/${archive}\""
    , "          tmpdir=\"$(mktemp -d)\""
    , "          curl -fsSL \"${url}\" -o \"${tmpdir}/${archive}\""
    , "          tar -xzf \"${tmpdir}/${archive}\" -C \"${tmpdir}\""
    , "          install -m 0755 \"${tmpdir}/gitleaks\" \"${HOME}/.local/bin/gitleaks\" 2>/dev/null || sudo install -m 0755 \"${tmpdir}/gitleaks\" /usr/local/bin/gitleaks"
    , ""
    , "      - name: Gitleaks detect"
    , "        run: |"
    , "          git config --global --add safe.directory \"$GITHUB_WORKSPACE\""
    , "          gitleaks detect --source . --redact --verbose --exit-code 1 --report-format sarif --report-path gitleaks.sarif"
    , ""
    , "      - name: Upload Gitleaks SARIF"
    , "        if: always()"
    , "        uses: github/codeql-action/upload-sarif@v4"
    , "        with:"
    , "          sarif_file: gitleaks.sarif"
    ]
